version: "3"

services:
  chat-server:
    build: .
    ports:
      - "3002:3002"
    restart: on-failure
    depends_on:
      rabbitmq-server:
        condition: service_healthy
  
  rabbitmq-server:
    image: "rabbitmq:3.12-management"
    healthcheck:
      test: rabbitmq-diagnostics -q ping